name: quality

on:
  push:
    branches: [main, staging]
  pull_request:
    branches-ignore: [staging]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: format with prettier
        run: npm run format

      - name: lint with eslint
        run: npm run lint

      - name: typecheck with vue-tsc
        run: npm run types
